VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "wheezy"
    config.vm.network "public_network"
    config.vm.provision :shell, :path => "provision/provision-salt-minion.sh", :privileged => true
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
    end

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end
end

# vim: ft=ruby
